# Generated by Django 3.1.6 on 2021-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channels',
            name='descriprion',
        ),
        migrations.AddField(
            model_name='channels',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
